export const skills = [
    "Web Development",
    "Graphic Design",
    "Digital Marketing",
    "Data Science",
    "Machine Learning",
    "Blockchain",
    "Public Speaking",
    "Photography",
    "Writing",
    "UI/UX Design",
    "Mobile App Development",
    "Cybersecurity",
    "Music Production",
    "3D Modeling",
    "AR/VR Development",
  ];